### ISSUE TITLE
Chapter 2, section Function overloading, page 37: empty functions used for overloading should not declare {} body

### ISSUE THREAD

**Issue by vkelman** [PacktPublishing/Learning-Angular-9--Third-Edition#4]
Correct me if I'm wrong, but instead of

```
function hello(names: string): string {}
function hello(names: string[]): string {}
function hello(names: any, greeting?: string): string { .  .  . }

```
the correct code should be

```
function hello(names: string): string;
function hello(names: string[]): string;
function hello(names: any, greeting?: string): string { .  .  .}
```

Also, it would be better to explain, in actual TypeScript code only first two signatures of a "hello" function call could be used, not the third one.  Without this remark it is not possible to understand how to use function overloading.
[StackOverflow](https://stackoverflow.com/a/13212871/236391)

**Comment by sonam-packt** [comment]
Thank you for the suggestion!
