### ISSUE TITLE
Property decorators examples don't work: pages 54-55

### ISSUE THREAD

**Issue by vkelman** [PacktPublishing/Learning-Angular-9--Third-Edition#5]
I tried to run Property decorators examples from pages 54-55 in TypeScript Playground.
It marks **this** in
```
 let propertyValue: string = this[key];
  if (delete this[key]) {

```
by read, saying that _'this' implicitly has type 'any' because it does not have a type annotation._

Running this example in a Playground does not produce any logs.
I'm new to TypeScript and don't understand how to fix those code samples.

**Comment by bampakoa** [comment]
@vkelman thanks for reporting this 🙏could you please check previous errata in https://github.com/PacktPublishing/Learning-Angular--Third-Edition#errata and let us know if the problem persists?
